### ISSUE TITLE
Ansible role

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [Tallguy297/SimpleHTTPServerWithUpload#3]
Hi,
Do you have any experience with Ansible?
We may try to create together ansible role that will install SimpleHTTPServerWithUpload.py and add systemd service for it. So it will be possible to start/stop HTTPServer by service.

**Comment by Tallguy297** [comment]
Hi Dzmitry,

 

I have never used Ansible and I don’t intend on using Ansible.

I am only using this script on a home media server to share movies, tv shows with family members.

 

With the “SimpleHTTPServerWithUpload.py” Python3 script,

I created a bash script called “SimpleHTTPServerWithUpload.sh” and put both in the /bin directory (personal choice).

The script is a simple 3 line routing to change the directory to /mnt/sdb1 and then call the Python script with an optional port argument.

Then I can copy, view or upload files. I find it fast than using samba file transfers.

 

I created a systemd service using Webmin, which I found very easy to use and configure services.

 

Thanks for you email.

Alex.
