### ISSUE TITLE
Can't find out file name

### ISSUE THREAD

**Issue by AGenchev** [Tallguy297/SimpleHTTPServerWithUpload#5]
Hello, I'm trying to upload this way:
time curl   -F  "file[]=@/home/user/chicken.jpg"  localhost:8000/
and I get (False, "Can't find out file name..." error

Also there's 1 second of **delay** no matter how big (or small) is the file. Do you have any idea why ?
The delay happens at the first call to line = self.rfile.readline() after that all is blazing fast.

**Comment by Tallguy297** [comment]
Why are you trying to write to the localhost:8000?
The hosting directory is defined in the bash script.

**Comment by AGenchev** [comment]
because the server is listening at port 8000 and is running at the localhost. The hosting directory does not matter. 
Hint: when I replaced the line:
`fn = re.findall(r'Content-Disposition.*name="file"; filename="(.*)"', line.decode())`
with
`fn = re.findall("filename\*?=([^;]+)", line.decode(), flags=re.IGNORECASE)`
it recognized the filename and saved it.
Though the 1-second delay on the same (local) host remains, which is not good.  
On Apache/PHP I get sub 30-ms delays for the same job.

**Comment by Tallguy297** [comment]
I am not very experienced in Python language, I am still learning.
I replaced line 121 of the python script with your regex expression.
1) Clicking upload by itself does not bring up an error message rather tries to upload an empty file.
2) Selecting a file, then upload results in filename incorrect encoding.

**Comment by AGenchev** [comment]
O.K. I wanted to use the code for different stuff - to send jobs to python from PHP because of the piles of ready stuff made for Python. I tried to solve the delay but in half a day I couldn't. So I left this and solved my problem by changing the approach - removed all web stuff and programmed one with low level TCP sockets. This time it worked without delays.
