### ISSUE TITLE
The line “ ‘Bytes’ if 0 == B > 1 else ‘Byte’ “  always results in ‘Byte’

### ISSUE THREAD

**Issue by YBPN** [Tallguy297/SimpleHTTPServerWithUpload#6]
I think the condition is evaluated as [False|True] > 1. It needs an “or”.

**Comment by Tallguy297** [comment]
Correct, but the only value being tested is B 0 or 1? So both statements would hold true.

**Comment by Tallguy297** [comment]
The statement on line 41 is actually correct.
`return '{0} {1}'.format(B,'Bytes' if 0 == B > 1 else 'Byte')`

In the statement the 0 is evaluated as an argument not a numeral.
So the condition is if argument 0 absolutely equals B > 1 then do nothing and print "Bytes" else print "Byte"

It's a little bit confusing but if you evaluate the rest of the code it makes sense.
