### ISSUE TITLE
Content-Type header doesn't contain boundary

### ISSUE THREAD

**Issue by arianaa30** [Tallguy297/SimpleHTTPServerWithUpload#9]
Hi,
The browser based form for upload works. But when I want to do it via CURL, it doesn't work:

curl.exe -X POST --upload-file file.pptx http://localhost:8000

`Content-Type header doesn't contain boundary`

**Comment by Tallguy297** [comment]
You can't do this using Curl.
This program generates a listing on local HTTP Server, which in this case is your computer using an IP of 0.0.0.0 Port 8000.
Uploading to this port, you are telling the computer to upload to a server that does not exist.
Easiest way is to copy the file using the `cp` or `rsync` command.

Thank you.
